### PR TITLE
Add pysteps vs machine learning section

### PR DESCRIPTION
**Pull request by loforest**
I added this section to ensure that pysteps is correctly used as benchmark for comparison of machine learning methods.

### CODE REVIEW

**Comment by dnerini** [comment]
Ciao @loforest ! 

Really nice idea, we definitely need to provide some clear guidelines on how pysteps can be used as benchmark to ML for nowcasting, way to go!

I will have a good read at your text and provide some feedback. Probably also  @pulkkins , @aperezhortal , @RubenImhoff, @franchg , @hydrogo and others might have some good suggestions and comments on the topic.

For the time being, I was just wondering whether the github page is a good place where to place your text. Maybe it would be better to have in the User guide on our RDT documentation? On the website we could leave a simpler and shorter section which introduces the topic and points to the documentation. What do you think?

**Comment by loforest** [comment]
Good!
I made a first attempt, but it was not easy to keep it concise.
I think it is a good idea to move the details somewhere in the doc/user
guide and only keep a short section on the github page (with a link).


Il Sab 4 Lug 2020, 11:14 Daniele Nerini <notifications@github.com> ha
scritto:

**Comment by RubenImhoff** [comment]
Nice work, @loforest! A useful piece of text, I would say.
I think I've nothing to add. I agree with @dnerini that this would fit well in the user guide.

**Review by dnerini — APPROVED** [review]
Perfect, thanks, we can merge this once the corresponding PR on the main pysteps  repo is merged

**Pull request merged**
